# Generated by Django 4.1 on 2022-09-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('llamados', models.IntegerField(default=0)),
                ('sospechosos', models.IntegerField(default=0)),
                ('descartados', models.IntegerField(default=0)),
                ('trasladados', models.IntegerField(default=0)),
                ('derivados', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
            },
        ),
    ]
