# Generated by Django 4.1 on 2022-09-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviles', '0002_alter_movil_habilitado_alter_movil_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movil',
            name='patente',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
